sudo: required

language: node_js

services:
- docker
- mongodb

branches:
  only:
  - master
  - /^greenkeeper/.*$/

before_install: npm install --global greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
- yarn test

after_script: greenkeeper-lockfile-upload

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./.deploy/build.sh && ./.deploy/deploy.sh; fi

cache:
  directories:
  - node_modules
  - ~/.mongodb-binaries
  yarn: true

notifications:
  email: false

notifications:
  slack:
    secure: "$SLACK_TOKEN"
