version: '3'

services:
  app:
    build:
      context: .
    volumes:
    - .:/home
    ports:
    - 3000:3000
    depends_on:
    - db
    command: bash -c 'npm rebuild node-sass --force && yarn start:dev'
    environment:
    - DB_USER=user
    - DB_PASS=pass
    - NODE_ENV=dev
    - DB_URL=db

  db:
    image: tutum/mongodb:3.2
    ports:
    - 27017:27017
    - 28017:28017
    environment:
    - AUTH=no
